import Foundation

enum SchoolCodes: String, CaseIterable {
    case cicsma
    case cicsst
    case encb
    case enmh
    case escasto
    case escatep
    case escom
    case ese
    case eseo
    case esfm
    case esiatec
    case esiatic
    case esiaz
    case esimeazc
    case esimecu
    case esimetic
    case esimez
    case esiqie
    case esm
    case esit
    case est
    case upibi
    case upiicsa
    case upiig
    case upiita
    case upiiz
    case enba
    case upiih
    case upiip
    case upiic
    case upiem
    case upiit
    
    case cet1
    case cecyt1
    case cecyt2
    case cecyt3
    case cecyt4
    case cecyt5
    case cecyt6
    case cecyt7
    case cecyt8
    case cecyt9
    case cecyt10
    case cecyt11
    case cecyt12
    case cecyt13
    case cecyt14
    case cecyt15
    case cecyt16
    case cecyt17
    case cecyt18
    case cecyt19
}
