import Foundation

struct HighSchoolConstants {
    static let cicsma = SchoolData(name: "CICS Milpa Alta", code: "cicsma", saes: "https://www.saes.cicsma.ipn.mx/")
    static let cicsst = SchoolData(name: "CICS UST", code: "cicsst", saes: "https://www.saes.cicsst.ipn.mx/")
    static let encb = SchoolData(name: "ENCB", code: "encb", saes: "https://www.saes.encb.ipn.mx/")
    static let enmh = SchoolData(name: "ENMH", code: "enmh", saes: "https://www.saes.enmh.ipn.mx")
    static let escasto = SchoolData(name: "ESCA Santo Tomas", code: "escasto", saes: "https://www.saes.escasto.ipn.mx/")
    static let escatep = SchoolData(name: "ESCA Tepepan", code: "escatep", saes: "https://www.saes.escatep.ipn.mx/")
    static let escom = SchoolData(name: "ESCOM", code: "escom", saes: "https://www.saes.escom.ipn.mx/")
    static let ese = SchoolData(name: "ESE", code: "ese", saes: "https://www.saes.ese.ipn.mx/")
    static let eseo = SchoolData(name: "ESEO", code: "eseo", saes: "https://www.saes.eseo.ipn.mx/")
    static let esfm = SchoolData(name: "ESFM", code: "esfm", saes: "https://www.saes.esfm.ipn.mx/")
    static let esiatec = SchoolData(name: "ESIA Tecamachalco", code: "esiatec", saes: "https://www.saes.esiatec.ipn.mx/")
    static let esiatic = SchoolData(name: "ESIA Ticoman", code: "esiatic", saes: "https://www.saes.esiatic.ipn.mx/")
    static let esiaz = SchoolData(name: "ESIA-ZAC", code: "esiaz", saes: "https://www.saes.esiaz.ipn.mx/")
    static let esimeazc = SchoolData(name: "ESIME AZCAPOTZALCO", code: "esimeazc", saes: "https://www.saes.esimeazc.ipn.mx/")
    static let esimecu = SchoolData(name: "ESIME CULHUACAN", code: "esimecu", saes: "https://www.saes.esimecu.ipn.mx/")
    static let esimetic = SchoolData(name: "ESIME TICOMAN", code: "esimetic", saes: "https://www.saes.esimetic.ipn.mx/")
    static let esimez = SchoolData(name: "ESIME ZACATENCO", code: "esimez", saes: "https://www.saes.esimez.ipn.mx/")
    static let esiqie = SchoolData(name: "ESIQUIE", code: "esiqie", saes: "https://www.saes.esiqie.ipn.mx/")
    static let esm = SchoolData(name: "ESM", code: "esm", saes: "https://www.saes.esm.ipn.mx/")
    static let esit = SchoolData(name: "ESIT", code: "esit", saes: "https://www.saes.esit.ipn.mx/")
    static let est = SchoolData(name: "EST", code: "est", saes: "https://www.saes.est.ipn.mx/")
    static let upibi = SchoolData(name: "UPIBI", code: "upibi", saes: "https://www.saes.upibi.ipn.mx/")
    static let upiicsa = SchoolData(name: "UPIICSA", code: "upiicsa", saes: "https://www.saes.upiicsa.ipn.mx/")
    static let upiig = SchoolData(name: "UPIIG", code: "upiig", saes: "https://www.saes.upiig.ipn.mx/")
    static let upiita = SchoolData(name: "UPIITA", code: "upiita", saes: "https://www.saes.upiita.ipn.mx/")
    static let upiiz = SchoolData(name: "UPIIZ", code: "upiiz", saes: "https://www.saes.upiiz.ipn.mx/")
    static let enba = SchoolData(name: "ENBA", code: "enba", saes: "https://www.saes.enba.ipn.mx/")
    static let upiih = SchoolData(name: "UPIIH", code: "upiih", saes: "https://www.saes.upiih.ipn.mx/")
    static let upiip = SchoolData(name: "UPIIP", code: "upiip", saes: "https://www.saes.upiip.ipn.mx/")
    static let upiic = SchoolData(name: "UPIIC", code: "upiic", saes: "https://www.saes.upiic.ipn.mx/")
    static let upiem = SchoolData(name: "UPIEM", code: "upiem", saes: "https://www.saes.upiem.ipn.mx/")
    static let upiit = SchoolData(name: "UPIIT", code: "upiit", saes: "https://www.saes.upiit.ipn.mx/")
}
